(SIMP-4015) Fix failure on tmp_mount fact on RHEL5 (#126)
The "findmnt" command does not exist on RHEL5 (and is not
available, afaict) and this causes an error:

undefined method `split' for nil:NilClass in tmp_mounts.rb.

The fix I chose to implement just skips the code block if "findmnt" returns no output.

SIMP-4015 #close